In [34]:
print("Table Weather Impact")
weather=spark.table("iceberg.gold.weather_impact")
weather.printSchema()
weather.limit(5).toPandas()

Table Weather Impact
root
 |-- pickup_date: date (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- is_rainy: boolean (nullable = true)
 |-- is_cold: boolean (nullable = true)
 |-- total_trips: long (nullable = true)
 |-- avg_distance: double (nullable = true)
 |-- avg_duration: double (nullable = true)
 |-- avg_fare: double (nullable = true)
 |-- avg_speed: double (nullable = true)
 |-- avg_tip_pct: double (nullable = true)
 |-- avg_temp: double (nullable = true)
 |-- avg_rhum: double (nullable = true)
 |-- avg_prcp: double (nullable = true)
 |-- avg_wspd: double (nullable = true)
 |-- avg_pres: double (nullable = true)
 |-- weather_condition: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)

,pickup_date,tpep_pickup_datetime,is_rainy,is_cold,total_trips,avg_distance,avg_duration,avg_fare,avg_speed,avg_tip_pct,avg_temp,avg_rhum,avg_prcp,avg_wspd,avg_pres,weather_condition,year,month
0,2025-10-01,2025-10-01 00:31:03,False,False,2,1.44,6.483333,17.73,16.591712,19.871795,21.0,66.0,0.0,15.0,1018.0,dry_warm,2025,10
1,2025-10-01,2025-10-01 00:43:53,False,False,1,2.79,7.783333,21.33,21.507495,13.033286,21.0,66.0,0.0,15.0,1018.0,dry_warm,2025,10
2,2025-10-01,2025-10-01 00:37:41,False,False,1,5.34,11.083333,29.15,28.908271,10.291595,21.0,66.0,0.0,15.0,1018.0,dry_warm,2025,10
3,2025-10-01,2025-10-01 01:32:08,False,False,1,0.74,4.100000,14.70,10.829268,16.666667,19.0,68.0,0.0,11.0,1018.0,dry_warm,2025,10
4,2025-10-01,2025-10-01 03:42:44,False,False,1,2.59,10.250000,19.20,15.160976,0.000000,19.0,63.0,0.0,15.0,1018.0,dry_warm,2025,10

In [38]:
print("Table Drivers Performance")
drivers=spark.table("iceberg.gold.driver_performance")
drivers.printSchema()
drivers.limit(5).toPandas()

Table Drivers Performance
root
 |-- VendorID: integer (nullable = true)
 |-- pickup_date: date (nullable = true)
 |-- trips_completed: long (nullable = true)
 |-- total_revenue: double (nullable = true)
 |-- avg_trip_duration: double (nullable = true)
 |-- avg_fare: double (nullable = true)
 |-- avg_speed: double (nullable = true)
 |-- total_tips: double (nullable = true)
 |-- avg_tip_percentage: double (nullable = true)
 |-- credit_card_trips: long (nullable = true)
 |-- cash_trips: long (nullable = true)
 |-- revenue_per_hour: double (nullable = true)
 |-- credit_card_percentage: double (nullable = true)
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)

,VendorID,pickup_date,trips_completed,total_revenue,avg_trip_duration,avg_fare,avg_speed,total_tips,avg_tip_percentage,credit_card_trips,cash_trips,revenue_per_hour,credit_card_percentage,year,month
0,2,2024-04-03,80897,2299031.99,17.077167,28.419249,9.626859,297646.44,12.689492,68493,11475,99.849987,84.666922,2024,4
1,2,2024-04-12,78513,2286753.48,16.384389,29.125794,10.753779,295016.84,12.488792,66232,11341,106.659313,84.358004,2024,4
2,1,2024-04-16,23750,659883.40,18.932945,27.784564,9.572269,79222.93,11.829306,20127,3343,88.051480,84.745263,2024,4
3,1,2024-04-12,25008,678413.18,17.791483,27.127846,9.822749,81101.43,11.762022,21201,3491,91.485954,84.776871,2024,4
4,2,2024-04-20,83340,2281607.42,16.000777,27.377099,10.921267,290774.18,12.351948,70147,12104,102.659133,84.169666,2024,4

In [39]:
print("hourly Pattern")
hourly=spark.table("iceberg.gold.hourly_patterns")
hourly.printSchema()
hourly.limit(5).toPandas()

hourly Pattern
root
 |-- pickup_date: date (nullable = true)
 |-- pickup_hour: integer (nullable = true)
 |-- trip_count: long (nullable = true)
 |-- avg_distance: double (nullable = true)
 |-- avg_duration: double (nullable = true)
 |-- avg_fare: double (nullable = true)
 |-- avg_speed: double (nullable = true)
 |-- avg_tip_pct: double (nullable = true)
 |-- weekend_trips: long (nullable = true)
 |-- weekday_trips: long (nullable = true)
 |-- hour_type: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)

  pickup_date  pickup_hour  trip_count  avg_distance  avg_duration   avg_fare  avg_speed  avg_tip_pct  weekend_trips  weekday_trips      hour_type  year  month
0  2024-04-07           12        5358      3.504188     14.894609  27.463899  11.987319    12.275662           5358              0  regular_hours  2024      4
1  2024-04-09           15        6286      3.471430     20.497041  29.706083   8.549887    11.922915              0           6286  regular_hours  2024      4
2  2024-04-22            6        1461      5.317728     16.841456  32.234189  16.744004    10.682682              0           1461   morning_rush  2024      4
3  2024-04-24           10        4636      3.210138     17.766667  28.092800   9.631849    12.255491              0           4636  regular_hours  2024      4
4  2024-04-27            1        3619      2.675048     12.057221  23.309796  12.076039    12.405097           3619              0          night  2024      4

In [41]:
print("Print Top Routes")
routes=spark.table("iceberg.gold.top_routes")
routes.printSchema()
routes.limit(5).toPandas()

Print Top Routes
root
 |-- route_id: string (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- pickup_date: date (nullable = true)
 |-- trip_count: long (nullable = true)
 |-- avg_distance: double (nullable = true)
 |-- avg_duration: double (nullable = true)
 |-- avg_fare: double (nullable = true)
 |-- avg_speed: double (nullable = true)
 |-- avg_tip_pct: double (nullable = true)
 |-- total_passengers: long (nullable = true)
 |-- efficiency_ratio: double (nullable = true)
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)

  route_id  PULocationID  DOLocationID pickup_date  trip_count  avg_distance  avg_duration   avg_fare  avg_speed  avg_tip_pct  total_passengers  efficiency_ratio  year  month
0  237_236           237           236  2024-04-17         998      1.070651      7.887325  16.355782   8.931578    13.468188              1272          0.135743  2024      4
1  237_236           237           236  2024-04-18         962      1.051185      8.065333  16.391632   8.809440    13.457276              1245          0.130334  2024      4
2  237_236           237           236  2024-04-05         952      1.065410      7.429902  16.091807   9.567776    13.304377              1263          0.143395  2024      4
3  237_236           237           236  2024-04-30         947      1.073506      7.432172  15.991563   9.474697    12.953844              1205          0.144440  2024      4
4  237_236           237           236  2024-04-09         935      1.080053      7.099376  15.943380  10.166890    13.449697              1162          0.152134  2024      4

In [42]:
print("Payment Analysis")
payment=spark.table("iceberg.gold.payment_analysis")
payment.printSchema()
payment.limit(5).toPandas()

Payment Analysis
root
 |-- pickup_date: date (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- trip_count: long (nullable = true)
 |-- total_revenue: double (nullable = true)
 |-- avg_fare: double (nullable = true)
 |-- total_tips: double (nullable = true)
 |-- avg_tip_pct: double (nullable = true)
 |-- avg_distance: double (nullable = true)
 |-- payment_type_label: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)

  pickup_date  payment_type  trip_count  total_revenue   avg_fare  total_tips  avg_tip_pct  avg_distance payment_type_label  year  month
0  2024-04-05             1       90301     2615057.17  28.959338   382584.38    14.541913      3.306086        credit_card  2024      4
1  2024-04-06             1       85948     2322171.50  27.018331   342322.07    14.629913      3.080849        credit_card  2024      4
2  2024-04-24             4         876       25360.76  28.950639       11.85     0.030061      4.237420            dispute  2024      4
3  2024-04-11             1       94406     2763677.73  29.274386   409574.76    14.724501      3.227486        credit_card  2024      4
4  2024-04-18             3         358        9069.54  25.333911        0.00     0.000000      3.272263          no_charge  2024      4